flask_app/models.py
from flask_app import db

class Materials(db.Model):
    __tablename__ = "materials"

    id = db.Column(db.Integer, primary_key=True)
    SO2 = db.Column(db.Float, nullable=False)
    NO2 = db.Column(db.Float, nullable=False)
    CO = db.Column(db.Float, nullable=False)
    O3 = db.Column(db.Integer, nullable=False)
    PM10 = db.Column(db.Integer, nullable=False)
    PM2_5 = db.Column(db.Integer, nullable=False)
    
    

flask_app/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired
from wtforms.fields import FloatField, IntegerField

class MaterialsForm(FlaskForm):
    SO2 = FloatField('오염수치', validators=[DataRequired('오염수치')])
    NO2 = FloatField('오염수치', validators=[DataRequired('오염수치')])
    CO = FloatField('오염수치', validators=[DataRequired('오염수치')])
    O3 = IntegerField('오염수치', validators=[DataRequired('오염수치')])
    PM10 = IntegerField('오염수치', validators=[DataRequired('오염수치')])
    PM2_5 = IntegerField('오염수치', validators=[DataRequired('오염수치')])

flask_app/__init__.py
import config
from flask import Flask
from flask_migrate import Migrate
from flask_sqlalchemy import SQLAlchemy
from flask import render_template

"""db객체를 create_app함수 안에서 생성하면 블루프린트와 같은 다른 모듈에서 불러올 수 없어서 
db, migrate와 같은 객체를 creat_app 함수 밖에서 생성하고
실제 객체 초기화는 create_app함수에서 init_app함수를 통해 진행"""
db = SQLAlchemy() 
migrate = Migrate()

def create_app():
    app = Flask(__name__)
    app.config.from_object(config) # config.py파일에 작성한 항목을 app.config 환경 변수로 부르기 위해 추가한 코드


    #ORM 
    db.init_app(app)
    # migrate.init_app(app, db) 
    if app.config['SQLALCHEMY_DATABASE_URI'].startswith("sqlite"):
        migrate.init_app(app, db, render_as_batch=True)
    else:
        migrate.init_app(app, db)
    from . import models

    #블루프린트
    from .views import index_view, predict_view
    app.register_blueprint(index_view.bp)
    app.register_blueprint(predict_view.bp)

    @app.route('/dashboard')
    def dashboard():
        return render_template('dashboard.html')

    return app


if __name__ == '__main__' : 
    app = create_app()
    app.run(debug=True)

flask_app/views/index_view.py
from flask import Blueprint
from flask import render_template

bp = Blueprint('main', __name__, url_prefix='/')

@bp.route('/')
def index():
    return render_template('index.html')

flask_app/views/predict_view.py
from flask import Blueprint, url_for
import pickle
from flask import render_template, request
from sklearn.ensemble import RandomForestClassifier

# from forms import MaterialsForm
from werkzeug.utils import redirect

bp = Blueprint('test', __name__, url_prefix='/predict')
model = pickle.load(open('airpollution.pkl', 'rb'))

#데이터 예측 처리
@bp.route('/predict', methods=['POST'])
def home():
    # form  = MaterialsForm()
    if request.method == 'POST':
        data1 = float(request.form['a'])
        data2 = float(request.form['b'])
        data3 = float(request.form['c'])
        data4 = float(request.form['d'])
        data5 = float(request.form['e'])
        data6 = float(request.form['f'])
        pred = model.predict([[data1, data2, data3, data4, data5, data6]])
        return render_template('after.html', data=pred) 

    else:
        return redirect(url_for('index.html'))

flask_app/templates/after.html
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">



<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, 그리고 Bootstrap 기여자들">
        <meta name="generator" content="Hugo 0.88.1">
        <title>AIR QUALITY LIKE?</title>
        <link rel="canonical" href="https://getbootstrap.kr/docs/5.1/examples/navbars/">
        <!-- Bootstrap core CSS -->
        <link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <!-- Favicons -->
        <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
        <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
        <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
        <meta name="theme-color" content="#7952b3">
            <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
        </meta>
        <style>
         .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;}
        @media (min-width: 768px) {
        .bd-placeholder-img-lg {
        font-size: 3.5rem;
        }
      }
    
        </style>
        <!-- Custom styles for this template -->
        <link href="navbar.css" rel="stylesheet">
    </head>
    <body class="d-flex h-100 text-center text-dark">
    
        <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
          <header class="mb-auto">
            <div><br>
              <h3 class="float-md-start mb-0">How's the SKY?</h3><br>
              <nav class="navbar navbar-dark bg-dark">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
                <a class="nav-link" href="https://www.keep.go.kr/portal/141?listStyle=&search_field=ALL&search_word=%EB%8C%80%EA%B8%B0">환경정보통</a>
                <a class="nav-link" href="http://www.me.go.kr/home/web/board/read.do?menuId=10392&boardMasterId=713&boardId=1457740">세계 환경의 날</a>
                <a class="nav-link" href="http://me.go.kr/BlueSky/main.html">푸른 하늘의 날</a>
                <a class="nav-link" href="https://www.google.com/search?q=%EB%8C%80%EA%B8%B0%EC%98%A4%EC%97%BC&rlz=1C5CHFA_enKR966KR966&source=lnms&tbm=nws&sa=X&ved=2ahUKEwiIiuPYycDzAhWLPXAKHRcGDRkQ_AUoAnoECAEQBA&biw=1120&bih=1124&dpr=2">관련기사</a>
                <a class="nav-link" href="/dashboard">DashBoard</a>
              </nav>
            </div>
          </header>

    <center>
     <main class="px-3">
    <h1>  PREDICTION :  </h1>
    <br><br>
    
    {%if data == 1%}
    <h1>Total air codition bad...</h1><br><br>
    <img src="{{url_for('static', filename='오염하늘.jpeg')}}">  

    {%else%}
    <h1>Total air condition good!</h1><br><br>
    <img src="{{url_for('static', filename='배경.jpeg')}}">
    
    
    {%endif%}

    <br><br>
    <a href='/'>Go back to home page</a>
    </main>
    </center>

</body>

</html>

flask_app/templates/dashboard.html
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, 그리고 Bootstrap 기여자들">
        <meta name="generator" content="Hugo 0.88.1">
        <title>AIR QUALITY LIKE?</title>
        <link rel="canonical" href="https://getbootstrap.kr/docs/5.1/examples/navbars/">
        <!-- Bootstrap core CSS -->
        <link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <!-- Favicons -->
        <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
        <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
        <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
        <meta name="theme-color" content="#7952b3">
            <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
        </meta>
        <style>
         .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;}
        @media (min-width: 768px) {
        .bd-placeholder-img-lg {
        font-size: 3.5rem;
        }
      }

        </style>
        <!-- Custom styles for this template -->
        <link href="navbar.css" rel="stylesheet">
    </head>
    <body class="d-flex h-100 text-center text-dark">
        <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
          <header class="mb-auto">
            <div><br>
                <h3 class="float-md-start mb-0">How's the SKY?</h3><br><br>
              <nav class="navbar navbar-dark bg-dark">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
                <a class="nav-link" href="https://www.keep.go.kr/portal/141?listStyle=&search_field=ALL&search_word=%EB%8C%80%EA%B8%B0">환경정보통</a>
                <a class="nav-link" href="http://www.me.go.kr/home/web/board/read.do?menuId=10392&boardMasterId=713&boardId=1457740">세계 환경의 날</a>
                <a class="nav-link" href="http://me.go.kr/BlueSky/main.html">푸른 하늘의 날</a>
                <a class="nav-link" href="https://www.google.com/search?q=%EB%8C%80%EA%B8%B0%EC%98%A4%EC%97%BC&rlz=1C5CHFA_enKR966KR966&source=lnms&tbm=nws&sa=X&ved=2ahUKEwiIiuPYycDzAhWLPXAKHRcGDRkQ_AUoAnoECAEQBA&biw=1120&bih=1124&dpr=2">관련기사</a>
                <a class="nav-link" href="/dashboard">DashBoard</a>
              </nav>
            </div>
          </header><br><br>
     
    
  
    <main>

    <h1>DashBoard</h1>
    <br>


    <iframe width="1200" height="900" src="https://datastudio.google.com/embed/reporting/b9b4983f-ccd3-4588-abb5-430dfd67c0c8/page/p_e3422sz9nc" frameborder="0" style="border:0" allowfullscreen></iframe>
      <br><br>

      <a href='/'>Go back to home page</a>
     </main>
    
    </body>
</html>

flask_app/templates/index.html
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">

<!DOCTYPE html>
<html lang="ko">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description" content="">
        <meta name="author" content="Mark Otto, Jacob Thornton, 그리고 Bootstrap 기여자들">
        <meta name="generator" content="Hugo 0.88.1">
        <title>AIR QUALITY LIKE?</title>
        <link rel="canonical" href="https://getbootstrap.kr/docs/5.1/examples/navbars/">
        <!-- Bootstrap core CSS -->
        <link href="/docs/5.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">
        <!-- Favicons -->
        <link rel="apple-touch-icon" href="/docs/5.1/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
        <link rel="manifest" href="/docs/5.1/assets/img/favicons/manifest.json">
        <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
        <link rel="icon" href="/docs/5.1/assets/img/favicons/favicon.ico">
        <meta name="theme-color" content="#7952b3">
            <link rel="mask-icon" href="/docs/5.1/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
        </meta>
        <style>
         .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;}
        @media (min-width: 768px) {
        .bd-placeholder-img-lg {
        font-size: 3.5rem;
        }
      }

        </style>
        <!-- Custom styles for this template -->
        <link href="navbar.css" rel="stylesheet">
    </head>
    <body class="d-flex h-100 text-center text-dark">
    
        <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
          <header class="mb-auto">
            <div><br>

              <h3 class="float-md-start mb-0">How's the SKY?</h3><br><br>
              <nav class="navbar navbar-dark bg-dark">
                <a class="nav-link active" aria-current="page" href="/">Home</a>
                <a class="nav-link" href="https://www.keep.go.kr/portal/141?listStyle=&search_field=ALL&search_word=%EB%8C%80%EA%B8%B0">환경정보통</a>
                <a class="nav-link" href="http://www.me.go.kr/home/web/board/read.do?menuId=10392&boardMasterId=713&boardId=1457740">세계 환경의 날</a>
                <a class="nav-link" href="http://me.go.kr/BlueSky/main.html">푸른 하늘의 날</a>
                <a class="nav-link" href="https://www.google.com/search?q=%EB%8C%80%EA%B8%B0%EC%98%A4%EC%97%BC&rlz=1C5CHFA_enKR966KR966&source=lnms&tbm=nws&sa=X&ved=2ahUKEwiIiuPYycDzAhWLPXAKHRcGDRkQ_AUoAnoECAEQBA&biw=1120&bih=1124&dpr=2">관련기사</a>
                <a class="nav-link" href="/dashboard">DashBoard</a>
              </nav>
            </div>
          </header><br><br>

    

          <main class="px-3"><br><br>
            <div class="body"></div>
                <h1>대기오염</h1><br><br>
                    <p class="lead">
                        <img src="{{url_for('static', filename='background.jpeg')}}" width="700" height="400"><br><br>

                    <b>WHO</b><br><br>
                    대기중에 인공적으로 배출된 오염물질이 존재하여<br><br>
                    오염물질의 양과 그 농도 및 지속시간이 어떤 지역 주민의 불쾌감을 일으키거나<br><br>
                    해당지역에 공중보건상 위해를 비치고 인간이나 동식물의 생활에 해를 주어<br><br>
                    도시민의 생활과 재산을 향유할 정당한 권리를 방해받은 상태</p><br><br><hr><br><br>

                

              
               
                <div class="row g-5">
                    <div class="col-md-5col-lg-4order-md-last">
                        <h4 class="d-flex jusrify-content-between align-items-center mb-3">
                            <span class="text-primary">INSERT YOUR VALUE!</span>
                        </h4><br>
                        <!-- <ul class="list-group mb-3"> -->
                        <form class="needs-validation" nvaate method="POST", action="{{url_for('test.home')}}">
                            <div class="row g-3">
                                <div class="col-12">
                                    <b> SO2 value:  <input type="text", name='a', placeholder="enter 1"> <br><br>
                                        NO2 value:  <input type="text", name='b', placeholder="enter 2"> <br><br>
                                        CO value:  <input type="text", name='c', placeholder="enter 3"> <br><br>
                                        O3 value:  <input type="text", name='d', placeholder="enter 4"> <br><br>
                                        PM10 value:  <input type="text", name='e', placeholder="enter 5"> <br><br>
                                        PM2.5 value: <input type="text", name='f', placeholder="enter 6"> <br><br><br></b>
                                        <input type="submit" , value='predict!' >
                                        <br><br><hr> 
                                </div>
                            </div>
                        <!-- </ul>    -->
                    </div>
                </div>
            </form>
        </main>
       
            <footer class="mt-auto text-dark-50">
                <p>Let's stop now <a href="https://github.com/ssu-jeong?tab=repositories" class="text-dark">PROJECT3</a>, by <a href="https://eight-viburnum-31d.notion.site/Study-5d06f2a3e52d41aba4fc65948ecd8274" class="text-dark">@AI_05</a>.</p><br><br>
              </footer>
            </div>
        </div>
    </body>
</html>